import { PluginDescriptor } from '@craftercms/studio-ui';
import Board from './components/Board';
import OpenBoardDialogPanelButton from './components/OpenBoardDialogPanelButton';
import ContentCommentsPanel from './components/contentComments/ContentCommentsPanel';
import ContentCommentsToolbarButton from './components/contentComments/ContentCommentsToolbarButton';
import NotificationsPanel from './components/notifications/NotificationsPanel';
import NotificationsToolbarButton from './components/notifications/NotificationsToolbarButton';
import TasksPanel from './components/tasks/TasksPanel';
import TasksToolbarButton from './components/tasks/TasksToolbarButton';
import CalendarDialog from './calendar/CalendarDialog';
import CalendarToolbarButton from './calendar/CalendarToolbarButton';
import ActiveWorkflowsToolbarButton from './components/activeWorkflows/ActiveWorkflowsToolbarButton';
import RecycleBinPanel from './components/recycleBin/RecycleBinPanel';
import RecycleBinToolbarButton from './components/recycleBin/RecycleBinToolbarButton';
import WorkflowBypassGuard from './components/workflowBypass/WorkflowBypassGuard';
import ProjectToolsConfiguration from './components/projectTools/ProjectToolsConfiguration';
import { projectToolsConfigurationWidgetId } from './consts';
declare const plugin: PluginDescriptor;
export { OpenBoardDialogPanelButton, Board, ContentCommentsPanel, ContentCommentsToolbarButton, NotificationsPanel, NotificationsToolbarButton, TasksPanel, TasksToolbarButton, CalendarDialog, CalendarToolbarButton, ActiveWorkflowsToolbarButton, RecycleBinPanel, RecycleBinToolbarButton, WorkflowBypassGuard, ProjectToolsConfiguration, projectToolsConfigurationWidgetId };
export default plugin;
